// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_entitlements.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertCustomerEntitlement = `-- name: InsertCustomerEntitlement :exec
INSERT INTO customer_entitlements (
    customer_id, vpn_fleet_id, expires_at, desired_version, last_command_number
) VALUES ($1, $2, $3, $4, $5)
`

type InsertCustomerEntitlementParams struct {
	CustomerID        string
	VpnFleetID        int64
	ExpiresAt         time.Time
	DesiredVersion    int64
	LastCommandNumber pgtype.Numeric
}

// Создаёт корневую строку первым успешным Apply. Вставка, а не upsert:
// отсутствие строки уже установлено под lock, а конфликт по первичному ключу
// означал бы, что сериализация на корневой строке не сработала, и такое обязано
// провалить команду, а не тихо перезаписать чужое состояние.
func (q *Queries) InsertCustomerEntitlement(ctx context.Context, arg InsertCustomerEntitlementParams) error {
	_, err := q.db.Exec(ctx, insertCustomerEntitlement,
		arg.CustomerID,
		arg.VpnFleetID,
		arg.ExpiresAt,
		arg.DesiredVersion,
		arg.LastCommandNumber,
	)
	return err
}

const lockCustomerEntitlement = `-- name: LockCustomerEntitlement :one

SELECT customer_id, vpn_fleet_id, expires_at, desired_version, last_command_number, created_at, updated_at
FROM customer_entitlements
WHERE customer_id = $1
FOR UPDATE
`

// Запросы к корневой строке customer.
// Блокирует корневую строку customer — первый шаг любой транзакции, меняющей
// состояние одного customer (нормативный порядок блокировок). Отсутствие
// строки означает нового customer.
func (q *Queries) LockCustomerEntitlement(ctx context.Context, customerID string) (CustomerEntitlement, error) {
	row := q.db.QueryRow(ctx, lockCustomerEntitlement, customerID)
	var i CustomerEntitlement
	err := row.Scan(
		&i.CustomerID,
		&i.VpnFleetID,
		&i.ExpiresAt,
		&i.DesiredVersion,
		&i.LastCommandNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerEntitlement = `-- name: UpdateCustomerEntitlement :exec
UPDATE customer_entitlements
SET expires_at = $2,
    desired_version = $3,
    last_command_number = $4,
    updated_at = now()
WHERE customer_id = $1
`

type UpdateCustomerEntitlementParams struct {
	CustomerID        string
	ExpiresAt         time.Time
	DesiredVersion    int64
	LastCommandNumber pgtype.Numeric
}

// Фиксирует принятую команду существующего customer. last_command_number
// двигается при успешном commit, в том числе на валидном no-op;
// отклонённые команды сюда не доходят. vpn_fleet_id не обновляется: смена fleet в
// v1 запрещена и отсекается доменом раньше.
func (q *Queries) UpdateCustomerEntitlement(ctx context.Context, arg UpdateCustomerEntitlementParams) error {
	_, err := q.db.Exec(ctx, updateCustomerEntitlement,
		arg.CustomerID,
		arg.ExpiresAt,
		arg.DesiredVersion,
		arg.LastCommandNumber,
	)
	return err
}
