// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_entitlements.sql

package db

import (
	"context"
)

const lockCustomerEntitlement = `-- name: LockCustomerEntitlement :one

SELECT customer_id, vpn_fleet_id, expires_at, desired_version, last_command_number, created_at, updated_at
FROM customer_entitlements
WHERE customer_id = $1
FOR UPDATE
`

// Запросы к корневой строке customer (§5, §11.1).
// Блокирует корневую строку customer — первый шаг любой транзакции, меняющей
// состояние одного customer (нормативный порядок блокировок, §11.1). Отсутствие
// строки означает нового customer.
func (q *Queries) LockCustomerEntitlement(ctx context.Context, customerID string) (CustomerEntitlement, error) {
	row := q.db.QueryRow(ctx, lockCustomerEntitlement, customerID)
	var i CustomerEntitlement
	err := row.Scan(
		&i.CustomerID,
		&i.VpnFleetID,
		&i.ExpiresAt,
		&i.DesiredVersion,
		&i.LastCommandNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
