// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dispatch.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeOperation = `-- name: CompleteOperation :exec
UPDATE agent_operations
SET status             = $1::text,
    next_attempt_at    = $2,
    completed_at       = CASE WHEN $3::boolean THEN now() ELSE NULL END,
    last_error_code    = $4::text,
    last_error_message = $5::text,
    lease_owner        = NULL,
    lease_expires_at   = NULL
WHERE operation_id = $6
`

type CompleteOperationParams struct {
	Status        string
	NextAttemptAt *time.Time
	Completed     bool
	ErrorCode     string
	ErrorMessage  string
	OperationID   uuid.UUID
}

// Записывает терминальный либо ожидающий повтора статус операции (§9).
//
// Lease снимается всегда: операция либо завершена, либо ждёт next_attempt_at, и в
// обоих случаях ноду держать больше не за что. Диагностика агента кладётся в
// last_error_* как есть — она уже санитизирована на его стороне и секретов не
// содержит (§9, §15).
func (q *Queries) CompleteOperation(ctx context.Context, arg CompleteOperationParams) error {
	_, err := q.db.Exec(ctx, completeOperation,
		arg.Status,
		arg.NextAttemptAt,
		arg.Completed,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.OperationID,
	)
	return err
}

const leaseNextOperation = `-- name: LeaseNextOperation :one
WITH leased AS (
    UPDATE agent_operations
    SET status           = 'IN_FLIGHT',
        attempt_count    = attempt_count + 1,
        lease_owner      = $1::text,
        lease_expires_at = now() + make_interval(secs => $2::int),
        next_attempt_at  = NULL
    WHERE operation_id = (
        SELECT o.operation_id
        FROM agent_operations o
        WHERE o.status IN ('PENDING', 'RETRY_WAIT')
          AND o.next_attempt_at <= now()
          AND NOT EXISTS (
              SELECT 1
              FROM agent_operations f
              WHERE f.node_id = o.node_id
                AND f.status = 'IN_FLIGHT'
          )
        ORDER BY o.next_attempt_at, o.operation_id
        FOR UPDATE SKIP LOCKED
        LIMIT 1
    )
    RETURNING operation_id, node_id, access_id, operation_type, desired_version, attempt_count
)
SELECT l.operation_id,
       l.node_id,
       l.access_id,
       l.operation_type,
       l.desired_version,
       l.attempt_count,
       a.desired_version AS access_desired_version,
       a.accounting_id,
       a.egress_key,
       (CASE WHEN l.operation_type = 'ENSURE_PRESENT'
             THEN a.encrypted_client_uuid END)::bytea AS encrypted_client_uuid,
       (CASE WHEN l.operation_type = 'ENSURE_PRESENT'
             THEN a.encryption_key_id ELSE '' END)::text AS encryption_key_id,
       n.agent_config,
       n.public_config
FROM leased l
JOIN vpn_accesses a ON a.access_id = l.access_id
JOIN vpn_nodes n ON n.node_id = l.node_id
`

type LeaseNextOperationParams struct {
	Owner        string
	LeaseSeconds int32
}

type LeaseNextOperationRow struct {
	OperationID          uuid.UUID
	NodeID               string
	AccessID             uuid.UUID
	OperationType        string
	DesiredVersion       int64
	AttemptCount         int32
	AccessDesiredVersion int64
	AccountingID         string
	EgressKey            string
	EncryptedClientUuid  []byte
	EncryptionKeyID      string
	AgentConfig          []byte
	PublicConfig         []byte
}

// Берёт lease готовой к отправке операции и сразу отдаёт payload (§9, §11.1).
//
// Гейт «на этой ноде нет IN_FLIGHT» отсекает конкурента по требованию §9
// «одновременно на одну ноду отправляется не более одной mutating operation». Сам
// по себе он неполон: два воркера читают один committed-снимок и оба его проходят.
// Инвариант держит partial unique index agent_operations_single_in_flight_per_node,
// а этот гейт лишь избавляет от лишних unique violation в обычном случае.
//
// Протухшая IN_FLIGHT ноду тоже держит, и это намеренно: слот освобождает сборщик
// выше, в той же транзакции. Иначе гейт расходился бы с индексом, и каждая попытка
// на такой ноде стоила бы отката.
//
// attempt_count увеличивается здесь, а не при записи результата: воркер, упавший
// после RPC, иначе не оставил бы следа попытки и backoff не рос бы по кругу
// (решение 48). Первая неудача приходит в домен со счётчиком 1, что даёт заявленную
// §9 начальную задержку в секунду.
//
// Payload собирается из АКТУАЛЬНЫХ строк access и ноды, а не из операции: §9 прямо
// запрещает хранить его в outbox. encrypted_client_uuid читается только для
// ENSURE_PRESENT — удаление матчится по accounting_id, и выносить ради него секрет
// в память незачем (§7, §9).
//
// access_desired_version возвращается для проверки перед RPC: если версия уже ушла
// вперёд, звонить агенту не нужно вовсе.
func (q *Queries) LeaseNextOperation(ctx context.Context, arg LeaseNextOperationParams) (LeaseNextOperationRow, error) {
	row := q.db.QueryRow(ctx, leaseNextOperation, arg.Owner, arg.LeaseSeconds)
	var i LeaseNextOperationRow
	err := row.Scan(
		&i.OperationID,
		&i.NodeID,
		&i.AccessID,
		&i.OperationType,
		&i.DesiredVersion,
		&i.AttemptCount,
		&i.AccessDesiredVersion,
		&i.AccountingID,
		&i.EgressKey,
		&i.EncryptedClientUuid,
		&i.EncryptionKeyID,
		&i.AgentConfig,
		&i.PublicConfig,
	)
	return i, err
}

const reapExpiredOperationLeases = `-- name: ReapExpiredOperationLeases :execrows

UPDATE agent_operations o
SET status = CASE WHEN a.desired_version > o.desired_version
                  THEN 'SUPERSEDED' ELSE 'RETRY_WAIT' END,
    completed_at = CASE WHEN a.desired_version > o.desired_version
                        THEN now() ELSE NULL END,
    next_attempt_at = CASE WHEN a.desired_version > o.desired_version
                           THEN NULL ELSE now() END,
    lease_owner      = NULL,
    lease_expires_at = NULL
FROM vpn_accesses a
WHERE a.access_id = o.access_id
  AND o.operation_id IN (
      SELECT e.operation_id
      FROM agent_operations e
      WHERE e.status = 'IN_FLIGHT'
        AND e.lease_expires_at < now()
      ORDER BY e.lease_expires_at
      FOR UPDATE SKIP LOCKED
      LIMIT $1::int
  )
`

// Диспетчер agent-операций: чтение outbox и запись исходов доставки (§9, §11.1).
//
// Транзакций здесь две, и между ними идёт сетевой вызов: §11.1 запрещает держать
// открытую транзакцию во время обращения к node-agent. Первая берёт lease и
// собирает payload, вторая записывает результат.
// Собирает операции, чей lease протух: воркер, взявший их, до записи результата не
// дожил (§9).
//
// Развилка ровно та, что описана в §9: устаревшая desired_version не повторяется
// никогда и становится терминальной SUPERSEDED, актуальная возвращается в очередь.
// next_attempt_at = now(), а не now() + backoff: lease протух из-за смерти воркера,
// а не из-за отказа ноды, и сам TTL уже был паузой (решение 49).
//
// attempt_count не трогается: он был увеличен при взятии lease (решение 48), и
// попытка действительно состоялась — backend просто не узнал, чем она кончилась.
//
// SKIP LOCKED и LIMIT, потому что сборщиков восемь: без них все восемь встали бы в
// очередь на один и тот же набор строк.
func (q *Queries) ReapExpiredOperationLeases(ctx context.Context, maxReaped int32) (int64, error) {
	result, err := q.db.Exec(ctx, reapExpiredOperationLeases, maxReaped)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAccessApplyState = `-- name: SetAccessApplyState :execrows
UPDATE vpn_accesses
SET apply_state = $1::text
WHERE access_id = $2
  AND desired_version = $3
`

type SetAccessApplyStateParams struct {
	ApplyState     string
	AccessID       uuid.UUID
	DesiredVersion int64
}

// Проецирует исход доставки на строку access с повторной проверкой desired_version
// (§11.1).
//
// Проверка живёт в WHERE, а не в отдельном чтении, потому что только так она
// атомарна: под READ COMMITTED конкурирующий UPDATE этой строки заставит наш
// дождаться его commit и перепроверить условие уже по новой версии строки. Ушедшая
// вперёд desired_version даёт ноль затронутых строк — ровно то, чего требует §11.1
// («результат устаревшей operation не меняет apply_state актуальной desired
// version»).
//
// Ноль строк — это ещё и ответ на вопрос «устарела ли операция», по которому
// вызывающий решает судьбу самой операции (решение 47). Отдельного SELECT для этого
// не нужно.
func (q *Queries) SetAccessApplyState(ctx context.Context, arg SetAccessApplyStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAccessApplyState, arg.ApplyState, arg.AccessID, arg.DesiredVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
