// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expiry.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const lockNextDueExpiredCustomer = `-- name: LockNextDueExpiredCustomer :one

SELECT customer_id, vpn_fleet_id, expires_at, desired_version, last_command_number,
       created_at, updated_at
FROM customer_entitlements e
WHERE e.expires_at <= now()
  AND e.lifecycle_state = 'ACTIVE'
  AND EXISTS (
      SELECT 1
      FROM vpn_accesses a
      WHERE a.customer_id = e.customer_id
        AND a.desired_state = 'PRESENT'
        AND a.retired_at IS NULL
  )
ORDER BY e.expires_at, e.customer_id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

type LockNextDueExpiredCustomerRow struct {
	CustomerID        string
	VpnFleetID        *int64
	ExpiresAt         *time.Time
	DesiredVersion    int64
	LastCommandNumber pgtype.Numeric
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// Expiry worker.
//
// Записей у него своих нет: он переиспользует запросы командного пути и
// материализации. Ниже единственное, чего у них не было, — выборка due customer.
// Берёт одного истёкшего customer, у которого ещё осталось что снимать.
//
// FOR UPDATE SKIP LOCKED здесь и есть вся координация: ни джобы, ни lease, ни
// курсора воркеру не нужно. Занятого customer вторая реплика не ждёт,
// а сразу берёт следующего; повторный запуск безопасен по построению.
//
// Условие на PRESENT-access обязательно, и не ради аккуратности: без него уже
// погашенный customer оставался бы due навсегда, воркер строил бы по нему пустые
// планы и никогда не сообщал бы о простое — то есть крутился бы вхолостую на
// полной скорости цикла. Оно же закрывает требование «повторный запуск и
// несколько worker replicas не создают неограниченного числа Remove operations».
//
// Ретайрнутые access в условие не входят: они уже ABSENT, и снимать с них нечего.
//
// Строка возвращается целиком, а не одним customer_id: expires_at из неё
// перечитывается под locком и задаёт план, чтобы expiry не снёс доступ после уже
// закоммиченного renewal.
func (q *Queries) LockNextDueExpiredCustomer(ctx context.Context) (LockNextDueExpiredCustomerRow, error) {
	row := q.db.QueryRow(ctx, lockNextDueExpiredCustomer)
	var i LockNextDueExpiredCustomerRow
	err := row.Scan(
		&i.CustomerID,
		&i.VpnFleetID,
		&i.ExpiresAt,
		&i.DesiredVersion,
		&i.LastCommandNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
