// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lifecycle.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const customerDeletionReady = `-- name: CustomerDeletionReady :one
SELECT NOT EXISTS (
    SELECT 1
    FROM vpn_accesses a
    WHERE a.customer_id = $1
      AND (a.desired_state <> 'ABSENT' OR a.apply_state <> 'APPLIED')
) AND NOT EXISTS (
    SELECT 1
    FROM agent_operations o
    JOIN vpn_accesses a ON a.access_id = o.access_id
    WHERE a.customer_id = $1
      AND o.status IN ('PENDING', 'RETRY_WAIT', 'IN_FLIGHT')
)::boolean AS ready
`

// true означает, что каждый текущий access подтверждён как ABSENT и ни одна
// актуальная операция ещё не выполняется/не ждёт.
func (q *Queries) CustomerDeletionReady(ctx context.Context, customerID string) (*bool, error) {
	row := q.db.QueryRow(ctx, customerDeletionReady, customerID)
	var ready *bool
	err := row.Scan(&ready)
	return ready, err
}

const deleteCustomerAccesses = `-- name: DeleteCustomerAccesses :exec
DELETE FROM vpn_accesses WHERE customer_id = $1
`

func (q *Queries) DeleteCustomerAccesses(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, deleteCustomerAccesses, customerID)
	return err
}

const deleteCustomerAgentOperations = `-- name: DeleteCustomerAgentOperations :exec
DELETE FROM agent_operations o
USING vpn_accesses a
WHERE a.customer_id = $1
  AND o.access_id = a.access_id
`

func (q *Queries) DeleteCustomerAgentOperations(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, deleteCustomerAgentOperations, customerID)
	return err
}

const deleteCustomerNodeUsage = `-- name: DeleteCustomerNodeUsage :exec
DELETE FROM node_quota_usage u
USING quota_periods p
WHERE p.customer_id = $1
  AND u.quota_period_id = p.quota_period_id
`

func (q *Queries) DeleteCustomerNodeUsage(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, deleteCustomerNodeUsage, customerID)
	return err
}

const deleteCustomerProcessedUsage = `-- name: DeleteCustomerProcessedUsage :exec
DELETE FROM traffic_usage_items_processed p
WHERE p.access_id IN (
          SELECT a.access_id FROM vpn_accesses a WHERE a.customer_id = $1
      )
   OR p.quota_period_id IN (
          SELECT qp.quota_period_id FROM quota_periods qp WHERE qp.customer_id = $1
      )
   OR p.accounting_id IN (
          SELECT a.accounting_id FROM vpn_accesses a WHERE a.customer_id = $1
      )
`

func (q *Queries) DeleteCustomerProcessedUsage(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, deleteCustomerProcessedUsage, customerID)
	return err
}

const deleteCustomerQuarantine = `-- name: DeleteCustomerQuarantine :exec
DELETE FROM traffic_batch_quarantine q
USING vpn_accesses a
WHERE a.customer_id = $1
  AND q.accounting_id = a.accounting_id
`

func (q *Queries) DeleteCustomerQuarantine(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, deleteCustomerQuarantine, customerID)
	return err
}

const deleteCustomerQuotaPeriods = `-- name: DeleteCustomerQuotaPeriods :exec
DELETE FROM quota_periods WHERE customer_id = $1
`

func (q *Queries) DeleteCustomerQuotaPeriods(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, deleteCustomerQuotaPeriods, customerID)
	return err
}

const finalizeCustomerTombstone = `-- name: FinalizeCustomerTombstone :exec
UPDATE customer_entitlements
SET vpn_fleet_id = NULL,
    expires_at = NULL,
    lifecycle_state = 'DELETED',
    delete_not_before = NULL,
    deleted_at = now(),
    updated_at = now()
WHERE customer_id = $1
  AND lifecycle_state = 'DELETING'
`

func (q *Queries) FinalizeCustomerTombstone(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, finalizeCustomerTombstone, customerID)
	return err
}

const insertDeletedCustomerTombstone = `-- name: InsertDeletedCustomerTombstone :exec

INSERT INTO customer_entitlements (
    customer_id, vpn_fleet_id, expires_at, desired_version,
    last_command_number, last_command_fingerprint, lifecycle_state, deleted_at
) VALUES ($1, NULL, NULL, 0, $2, $3, 'DELETED', now())
`

type InsertDeletedCustomerTombstoneParams struct {
	CustomerID             string
	LastCommandNumber      pgtype.Numeric
	LastCommandFingerprint []byte
}

// Administrative lifecycle and physical deletion.
func (q *Queries) InsertDeletedCustomerTombstone(ctx context.Context, arg InsertDeletedCustomerTombstoneParams) error {
	_, err := q.db.Exec(ctx, insertDeletedCustomerTombstone, arg.CustomerID, arg.LastCommandNumber, arg.LastCommandFingerprint)
	return err
}

const lockNextDeletionCandidate = `-- name: LockNextDeletionCandidate :one
SELECT customer_id, vpn_fleet_id, expires_at, desired_version, last_command_number, created_at, updated_at, lifecycle_state, last_command_fingerprint, delete_not_before, deleted_at
FROM customer_entitlements
WHERE lifecycle_state = 'DELETING'
  AND delete_not_before <= now()
  AND NOT EXISTS (
      SELECT 1
      FROM vpn_accesses a
      WHERE a.customer_id = customer_entitlements.customer_id
        AND (a.desired_state <> 'ABSENT' OR a.apply_state <> 'APPLIED')
  )
  AND NOT EXISTS (
      SELECT 1
      FROM agent_operations o
      JOIN vpn_accesses a ON a.access_id = o.access_id
      WHERE a.customer_id = customer_entitlements.customer_id
        AND o.status IN ('PENDING', 'RETRY_WAIT', 'IN_FLIGHT')
  )
ORDER BY delete_not_before, customer_id
FOR UPDATE SKIP LOCKED
LIMIT 1
`

func (q *Queries) LockNextDeletionCandidate(ctx context.Context) (CustomerEntitlement, error) {
	row := q.db.QueryRow(ctx, lockNextDeletionCandidate)
	var i CustomerEntitlement
	err := row.Scan(
		&i.CustomerID,
		&i.VpnFleetID,
		&i.ExpiresAt,
		&i.DesiredVersion,
		&i.LastCommandNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LifecycleState,
		&i.LastCommandFingerprint,
		&i.DeleteNotBefore,
		&i.DeletedAt,
	)
	return i, err
}
