// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manifest.sql

package db

import (
	"context"
)

const getLastManifestRevision = `-- name: GetLastManifestRevision :one
SELECT revision, digest
FROM manifest_revisions
ORDER BY revision DESC
LIMIT 1
`

type GetLastManifestRevisionRow struct {
	Revision int64
	Digest   string
}

// Последняя принятая revision и её canonical digest. Ноль строк означает,
// что манифест не принимался ни разу.
func (q *Queries) GetLastManifestRevision(ctx context.Context) (GetLastManifestRevisionRow, error) {
	row := q.db.QueryRow(ctx, getLastManifestRevision)
	var i GetLastManifestRevisionRow
	err := row.Scan(&i.Revision, &i.Digest)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    actor_type, actor_id, action, target_type, target_id,
    request_id, outcome, sanitized_metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditEventParams struct {
	ActorType         string
	ActorID           *string
	Action            string
	TargetType        *string
	TargetID          *string
	RequestID         *string
	Outcome           string
	SanitizedMetadata []byte
}

// Запись аудита. sanitized_metadata не содержит секретов и customer ID.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.Outcome,
		arg.SanitizedMetadata,
	)
	return err
}

const insertManifestRevision = `-- name: InsertManifestRevision :exec
INSERT INTO manifest_revisions (revision, digest, canonical_payload)
VALUES ($1, $2, $3)
`

type InsertManifestRevisionParams struct {
	Revision         int64
	Digest           string
	CanonicalPayload []byte
}

// Журнал принятых снапшотов. Вставка без ON CONFLICT: повтор revision сюда не
// доходит (идемпотентный отсекается раньше, конфликтующий отклоняется), поэтому
// нарушение первичного ключа означало бы сбой сериализации, а не штатный повтор.
func (q *Queries) InsertManifestRevision(ctx context.Context, arg InsertManifestRevisionParams) error {
	_, err := q.db.Exec(ctx, insertManifestRevision, arg.Revision, arg.Digest, arg.CanonicalPayload)
	return err
}

const insertMaterializationJob = `-- name: InsertMaterializationJob :exec
INSERT INTO manifest_materialization_jobs (revision, status)
VALUES ($1, 'PENDING')
`

// Durable-джоба fan-out customer access. Ставится в той же транзакции,
// что и проекция: иначе принятый снапшот остался бы без материализации.
func (q *Queries) InsertMaterializationJob(ctx context.Context, revision int64) error {
	_, err := q.db.Exec(ctx, insertMaterializationJob, revision)
	return err
}

const listAcceptedFleetIDs = `-- name: ListAcceptedFleetIDs :many
SELECT vpn_fleet_id
FROM vpn_fleets
ORDER BY vpn_fleet_id
`

// Все принятые fleet, а не только текущие: принятый vpn_fleet_id не удаляется и
// обязан присутствовать в каждом следующем снапшоте.
func (q *Queries) ListAcceptedFleetIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAcceptedFleetIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var vpn_fleet_id int64
		if err := rows.Scan(&vpn_fleet_id); err != nil {
			return nil, err
		}
		items = append(items, vpn_fleet_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBridgeRoutes = `-- name: ListAllBridgeRoutes :many
SELECT vpn_fleet_id, routing_key, entry_node_id, exit_node_id, current
FROM vpn_bridge_routes
ORDER BY vpn_fleet_id, routing_key
`

type ListAllBridgeRoutesRow struct {
	VpnFleetID  int64
	RoutingKey  string
	EntryNodeID string
	ExitNodeID  string
	Current     bool
}

// Все связи, включая удалённые: routing_key занят навсегда, и оживление его с
// другой парой (entry, exit) запрещено.
func (q *Queries) ListAllBridgeRoutes(ctx context.Context) ([]ListAllBridgeRoutesRow, error) {
	rows, err := q.db.Query(ctx, listAllBridgeRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBridgeRoutesRow{}
	for rows.Next() {
		var i ListAllBridgeRoutesRow
		if err := rows.Scan(
			&i.VpnFleetID,
			&i.RoutingKey,
			&i.EntryNodeID,
			&i.ExitNodeID,
			&i.Current,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentFleetMemberships = `-- name: ListCurrentFleetMemberships :many
SELECT vpn_fleet_id, node_id
FROM vpn_fleet_nodes
WHERE current
ORDER BY vpn_fleet_id, node_id
`

type ListCurrentFleetMembershipsRow struct {
	VpnFleetID int64
	NodeID     string
}

func (q *Queries) ListCurrentFleetMemberships(ctx context.Context) ([]ListCurrentFleetMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentFleetMemberships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentFleetMembershipsRow{}
	for rows.Next() {
		var i ListCurrentFleetMembershipsRow
		if err := rows.Scan(&i.VpnFleetID, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentNodeIDs = `-- name: ListCurrentNodeIDs :many
SELECT node_id
FROM vpn_nodes
WHERE current
ORDER BY node_id
`

// Ноды текущего снапшота: из них выводится, какие ноды из него исчезли.
func (q *Queries) ListCurrentNodeIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listCurrentNodeIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockManifestIngest = `-- name: LockManifestIngest :exec

SELECT pg_advisory_xact_lock($1::bigint)
`

// Приём infrastructure manifest и его проекция в таблицы топологии.
//
// Весь снапшот применяется одной транзакцией: атомарно
// или не применяется вообще». Физических удалений здесь нет ни одного — строки
// помечаются current = false и живут вечно.
// Сериализует приём манифеста: одновременно применяется не более одного снапшота.
//
// Приём манифеста читает всю проекцию и тут же её переписывает, поэтому без
// сериализации два параллельных вызова могли бы прочитать одну и ту же
// last_revision и разъехаться в решениях о destructive. Advisory lock снимается
// вместе с транзакцией и берётся до первого чтения.
//
// Цена нулевая: манифест применяет CI/CD инфраструктуры, это редкая операция, а
// команды customer этот lock не берут и не ждут.
func (q *Queries) LockManifestIngest(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, lockManifestIngest, lockKey)
	return err
}

const retireBridgeRoutes = `-- name: RetireBridgeRoutes :exec
UPDATE vpn_bridge_routes AS route
SET current = false
WHERE (route.vpn_fleet_id, route.routing_key) IN (
    SELECT fleets.vpn_fleet_id, keys.routing_key
    FROM unnest($1::bigint[]) WITH ORDINALITY AS fleets(vpn_fleet_id, position)
    JOIN unnest($2::text[]) WITH ORDINALITY AS keys(routing_key, position)
      ON fleets.position = keys.position
)
`

type RetireBridgeRoutesParams struct {
	FleetIds    []int64
	RoutingKeys []string
}

func (q *Queries) RetireBridgeRoutes(ctx context.Context, arg RetireBridgeRoutesParams) error {
	_, err := q.db.Exec(ctx, retireBridgeRoutes, arg.FleetIds, arg.RoutingKeys)
	return err
}

const retireFleetNodes = `-- name: RetireFleetNodes :exec
UPDATE vpn_fleet_nodes AS membership
SET current = false
WHERE (membership.vpn_fleet_id, membership.node_id) IN (
    SELECT fleets.vpn_fleet_id, nodes.node_id
    FROM unnest($1::bigint[]) WITH ORDINALITY AS fleets(vpn_fleet_id, position)
    JOIN unnest($2::text[]) WITH ORDINALITY AS nodes(node_id, position)
      ON fleets.position = nodes.position
)
`

type RetireFleetNodesParams struct {
	FleetIds []int64
	NodeIds  []string
}

// Два параллельных массива сшиваются по WITH ORDINALITY, а не многоаргументным
// unnest: последний анализатор sqlc не разбирает.
func (q *Queries) RetireFleetNodes(ctx context.Context, arg RetireFleetNodesParams) error {
	_, err := q.db.Exec(ctx, retireFleetNodes, arg.FleetIds, arg.NodeIds)
	return err
}

const retireNodes = `-- name: RetireNodes :exec
UPDATE vpn_nodes
SET current    = false,
    updated_at = now()
WHERE node_id = ANY($1::text[])
`

// Ноды, глобально исчезнувшие из манифеста. manifest_revision не трогается
// и остаётся последней revision, в которой нода присутствовала.
func (q *Queries) RetireNodes(ctx context.Context, nodeIds []string) error {
	_, err := q.db.Exec(ctx, retireNodes, nodeIds)
	return err
}

const upsertBridgeRoute = `-- name: UpsertBridgeRoute :exec
INSERT INTO vpn_bridge_routes (
    vpn_fleet_id, routing_key, entry_node_id, exit_node_id,
    egress_tag, display_name, manifest_revision, current
) VALUES ($1, $2, $3, $4, $5, $6, $7, true)
ON CONFLICT (vpn_fleet_id, routing_key) DO UPDATE
SET egress_tag        = EXCLUDED.egress_tag,
    display_name      = EXCLUDED.display_name,
    manifest_revision = EXCLUDED.manifest_revision,
    current           = true
`

type UpsertBridgeRouteParams struct {
	VpnFleetID       int64
	RoutingKey       string
	EntryNodeID      string
	ExitNodeID       string
	EgressTag        string
	DisplayName      string
	ManifestRevision int64
}

// Апсерт связи. entry_node_id и exit_node_id намеренно НЕ обновляются: пара
// неизменяема для существующего routing_key. Домен это проверяет и
// отклоняет манифест раньше; здесь то же правило закреплено структурно, чтобы
// будущая дыра в проверке не переставила молча входную ноду у выданных access.
func (q *Queries) UpsertBridgeRoute(ctx context.Context, arg UpsertBridgeRouteParams) error {
	_, err := q.db.Exec(ctx, upsertBridgeRoute,
		arg.VpnFleetID,
		arg.RoutingKey,
		arg.EntryNodeID,
		arg.ExitNodeID,
		arg.EgressTag,
		arg.DisplayName,
		arg.ManifestRevision,
	)
	return err
}

const upsertFleetNode = `-- name: UpsertFleetNode :exec
INSERT INTO vpn_fleet_nodes (vpn_fleet_id, node_id, manifest_revision, current)
VALUES ($1, $2, $3, true)
ON CONFLICT (vpn_fleet_id, node_id) DO UPDATE
SET manifest_revision = EXCLUDED.manifest_revision,
    current           = true
`

type UpsertFleetNodeParams struct {
	VpnFleetID       int64
	NodeID           string
	ManifestRevision int64
}

func (q *Queries) UpsertFleetNode(ctx context.Context, arg UpsertFleetNodeParams) error {
	_, err := q.db.Exec(ctx, upsertFleetNode, arg.VpnFleetID, arg.NodeID, arg.ManifestRevision)
	return err
}

const upsertVpnFleet = `-- name: UpsertVpnFleet :exec
INSERT INTO vpn_fleets (vpn_fleet_id, manifest_revision, current)
VALUES ($1, $2, true)
ON CONFLICT (vpn_fleet_id) DO UPDATE
SET manifest_revision = EXCLUDED.manifest_revision,
    current           = true,
    updated_at        = now()
`

type UpsertVpnFleetParams struct {
	VpnFleetID       int64
	ManifestRevision int64
}

func (q *Queries) UpsertVpnFleet(ctx context.Context, arg UpsertVpnFleetParams) error {
	_, err := q.db.Exec(ctx, upsertVpnFleet, arg.VpnFleetID, arg.ManifestRevision)
	return err
}

const upsertVpnNode = `-- name: UpsertVpnNode :exec
INSERT INTO vpn_nodes (node_id, agent_config, public_config, manifest_revision, current)
VALUES ($1, $2, $3, $4, true)
ON CONFLICT (node_id) DO UPDATE
SET agent_config      = EXCLUDED.agent_config,
    public_config     = EXCLUDED.public_config,
    manifest_revision = EXCLUDED.manifest_revision,
    current           = true,
    updated_at        = now()
`

type UpsertVpnNodeParams struct {
	NodeID           string
	AgentConfig      []byte
	PublicConfig     []byte
	ManifestRevision int64
}

// Апсерт ноды. Идентичность (node_id) стабильна, endpoint и публичные параметры
// изменяемы между revisions.
//
// desired_revision НЕ трогается: приём манифеста не меняет состав desired-юзеров
// ноды и не создаёт agent operations. Ноду, вернувшуюся в
// манифест, апсерт оживляет на месте — current снова true.
func (q *Queries) UpsertVpnNode(ctx context.Context, arg UpsertVpnNodeParams) error {
	_, err := q.db.Exec(ctx, upsertVpnNode,
		arg.NodeID,
		arg.AgentConfig,
		arg.PublicConfig,
		arg.ManifestRevision,
	)
	return err
}
