// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: materialize.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const advanceMaterializationCursor = `-- name: AdvanceMaterializationCursor :exec
UPDATE manifest_materialization_jobs
SET cursor     = jsonb_build_object('customer_id', $1::text),
    updated_at = now()
WHERE revision = $2
`

type AdvanceMaterializationCursorParams struct {
	CustomerID string
	Revision   int64
}

// Курсор двигается в той же транзакции, что и изменения customer.
func (q *Queries) AdvanceMaterializationCursor(ctx context.Context, arg AdvanceMaterializationCursorParams) error {
	_, err := q.db.Exec(ctx, advanceMaterializationCursor, arg.CustomerID, arg.Revision)
	return err
}

const bumpEntitlementDesiredVersion = `-- name: BumpEntitlementDesiredVersion :exec
UPDATE customer_entitlements
SET desired_version = $1,
    updated_at      = now()
WHERE customer_id = $2::text
`

type BumpEntitlementDesiredVersionParams struct {
	DesiredVersion int64
	CustomerID     string
}

// Двигает только desired_version корневой строки.
//
// Отдельный запрос, а не UpdateCustomerEntitlement: тот пишет ещё expires_at и
// last_command_number, а материализация не является командой product-сервиса и
// не имеет права трогать ни срок, ни счётчик команд.
func (q *Queries) BumpEntitlementDesiredVersion(ctx context.Context, arg BumpEntitlementDesiredVersionParams) error {
	_, err := q.db.Exec(ctx, bumpEntitlementDesiredVersion, arg.DesiredVersion, arg.CustomerID)
	return err
}

const claimMaterializationJob = `-- name: ClaimMaterializationJob :one

UPDATE manifest_materialization_jobs
SET status           = 'IN_PROGRESS',
    lease_owner      = $1::text,
    lease_expires_at = now() + make_interval(secs => $2::int),
    updated_at       = now()
WHERE revision = (
    SELECT revision
    FROM manifest_materialization_jobs
    WHERE status IN ('PENDING', 'IN_PROGRESS')
      AND (lease_expires_at IS NULL
           OR lease_expires_at < now()
           OR lease_owner = $1::text)
    ORDER BY revision
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING revision, coalesce(cursor->>'customer_id', '')::text AS cursor_customer_id
`

type ClaimMaterializationJobParams struct {
	Owner        string
	LeaseSeconds int32
}

type ClaimMaterializationJobRow struct {
	Revision         int64
	CursorCustomerID string
}

// Воркер материализации манифеста.
//
// Чтения состояния customer здесь не дублируются: они те же, что у
// ApplyCustomerAccess, и берутся из customer_entitlements.sql, quota_periods.sql,
// node_quota_usage.sql, topology.sql и vpn_accesses.sql. Ниже только то, чего у
// командного пути нет: координация джобы и записи, которых Apply не делает.
// Берёт в работу самую старую незавершённую джобу.
//
// SKIP LOCKED, чтобы вторая реплика не ждала на уже занятой строке, а сразу
// взяла следующую. Условие на lease разрешает три случая: джоба ещё ничья,
// чужой lease протух (воркер упал — требует восстановления), либо lease наш
// собственный. Последнее обязательно: каждый шаг ProcessNext идёт отдельной
// транзакцией, и без него воркер не смог бы продолжить собственную джобу.
func (q *Queries) ClaimMaterializationJob(ctx context.Context, arg ClaimMaterializationJobParams) (ClaimMaterializationJobRow, error) {
	row := q.db.QueryRow(ctx, claimMaterializationJob, arg.Owner, arg.LeaseSeconds)
	var i ClaimMaterializationJobRow
	err := row.Scan(&i.Revision, &i.CursorCustomerID)
	return i, err
}

const completeMaterializationJob = `-- name: CompleteMaterializationJob :exec
UPDATE manifest_materialization_jobs
SET status           = 'DONE',
    lease_owner      = NULL,
    lease_expires_at = NULL,
    updated_at       = now()
WHERE revision = $1
`

// Обход дошёл до конца. Lease снимается: перезапускать джобу больше не нужно.
func (q *Queries) CompleteMaterializationJob(ctx context.Context, revision int64) error {
	_, err := q.db.Exec(ctx, completeMaterializationJob, revision)
	return err
}

const nextCustomerAfter = `-- name: NextCustomerAfter :one
SELECT customer_id
FROM customer_entitlements
WHERE customer_id > $1::text
ORDER BY customer_id
LIMIT 1
`

// Следующий customer в порядке customer_id. Ноль строк означает, что обход
// завершён.
//
// Обходятся ВСЕ customer, а не только затронутые манифестом: удаления по
// manifest_revision не находятся — у ретайрнутых строк остаётся прежняя revision.
func (q *Queries) NextCustomerAfter(ctx context.Context, afterCustomerID string) (string, error) {
	row := q.db.QueryRow(ctx, nextCustomerAfter, afterCustomerID)
	var customer_id string
	err := row.Scan(&customer_id)
	return customer_id, err
}

const repointAccess = `-- name: RepointAccess :exec
UPDATE vpn_accesses
SET egress_key      = $1::text,
    desired_state   = $2::text,
    desired_version = $3,
    apply_state     = 'PENDING'
WHERE access_id = $4
`

type RepointAccessParams struct {
	EgressKey      string
	DesiredState   string
	DesiredVersion int64
	AccessID       uuid.UUID
}

// Смена egress_tag связи при неизменных routing_key и паре.
//
// client_uuid, accounting_id и generation сохраняются: это repoint, а не новое
// поколение. apply_state сбрасывается в PENDING — агенту предстоит переиздать
// персональное правило по новому egress_key.
func (q *Queries) RepointAccess(ctx context.Context, arg RepointAccessParams) error {
	_, err := q.db.Exec(ctx, repointAccess,
		arg.EgressKey,
		arg.DesiredState,
		arg.DesiredVersion,
		arg.AccessID,
	)
	return err
}

const retireAccess = `-- name: RetireAccess :exec
UPDATE vpn_accesses
SET retired_at      = now(),
    desired_state   = 'ABSENT',
    desired_version = $1,
    apply_state     = $2::text
WHERE access_id = $3
`

type RetireAccessParams struct {
	DesiredVersion int64
	ApplyState     string
	AccessID       uuid.UUID
}

// Цель исчезла из манифеста: access ретайрится и переводится в ABSENT.
//
// Строка не удаляется никогда — по ней приходит поздний traffic, а повторное
// появление цели создаёт новое поколение.
//
// apply_state приходит параметром, потому что зависит от того, доставляется ли
// удаление: на живую ноду выпускается EnsureUserAbsent и состояние PENDING, а на
// глобально удалённую доставлять нечего, и она сразу APPLIED — иначе операция
// висела бы недоставленной вечно.
func (q *Queries) RetireAccess(ctx context.Context, arg RetireAccessParams) error {
	_, err := q.db.Exec(ctx, retireAccess, arg.DesiredVersion, arg.ApplyState, arg.AccessID)
	return err
}
