// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentOperation struct {
	OperationID      uuid.UUID
	NodeID           string
	AccessID         uuid.UUID
	OperationType    string
	DesiredVersion   int64
	Status           string
	AttemptCount     int32
	NextAttemptAt    *time.Time
	LeaseOwner       *string
	LeaseExpiresAt   *time.Time
	LastErrorCode    *string
	LastErrorMessage *string
	CreatedAt        time.Time
	CompletedAt      *time.Time
}

type AuditEvent struct {
	AuditID           uuid.UUID
	OccurredAt        time.Time
	ActorType         string
	ActorID           *string
	Action            string
	TargetType        *string
	TargetID          *string
	RequestID         *string
	Outcome           string
	SanitizedMetadata []byte
}

type CustomerEntitlement struct {
	CustomerID        string
	VpnFleetID        int64
	ExpiresAt         time.Time
	DesiredVersion    int64
	LastCommandNumber pgtype.Numeric
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ManifestMaterializationJob struct {
	Revision       int64
	Cursor         []byte
	Status         string
	LeaseOwner     *string
	LeaseExpiresAt *time.Time
	UpdatedAt      time.Time
}

type ManifestRevision struct {
	Revision         int64
	Digest           string
	CanonicalPayload []byte
	AppliedAt        time.Time
}

type NodeQuotaUsage struct {
	QuotaPeriodID uuid.UUID
	NodeID        string
	UplinkBytes   pgtype.Numeric
	DownlinkBytes pgtype.Numeric
	TotalBytes    pgtype.Numeric
	ExhaustedAt   *time.Time
	UpdatedAt     time.Time
}

type NodeUsageCursor struct {
	NodeID         string
	SpoolID        string
	AckedSequence  pgtype.Numeric
	LeaseOwner     *string
	LeaseExpiresAt *time.Time
	UpdatedAt      time.Time
}

type QuotaPeriod struct {
	QuotaPeriodID   uuid.UUID
	CustomerID      string
	StartedAt       time.Time
	ClosedAt        *time.Time
	UsageQuotaBytes pgtype.Numeric
}

type TrafficBatchQuarantine struct {
	QuarantineID     uuid.UUID
	NodeID           string
	SpoolID          string
	Sequence         pgtype.Numeric
	AccountingID     *string
	Reason           string
	SanitizedPayload []byte
	CreatedAt        time.Time
}

type TrafficUsageItemsProcessed struct {
	NodeID        string
	SpoolID       string
	Sequence      pgtype.Numeric
	AccountingID  string
	AccessID      *uuid.UUID
	QuotaPeriodID *uuid.UUID
	Result        string
	ProcessedAt   time.Time
}

type VpnAccess struct {
	AccessID            uuid.UUID
	CustomerID          string
	Kind                string
	LogicalTargetKey    string
	Generation          int32
	EntryNodeID         string
	EgressKey           string
	AccountingID        string
	EncryptedClientUuid []byte
	EncryptionKeyID     string
	DesiredState        string
	ApplyState          string
	DesiredVersion      int64
	CreatedAt           time.Time
	RetiredAt           *time.Time
}

type VpnBridgeRoute struct {
	VpnFleetID       int64
	RoutingKey       string
	EntryNodeID      string
	ExitNodeID       string
	EgressTag        string
	DisplayName      string
	ManifestRevision int64
	Current          bool
}

type VpnFleet struct {
	VpnFleetID       int64
	ManifestRevision int64
	Current          bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type VpnFleetNode struct {
	VpnFleetID       int64
	NodeID           string
	ManifestRevision int64
	Current          bool
}

type VpnNode struct {
	NodeID           string
	AgentConfig      []byte
	PublicConfig     []byte
	DesiredRevision  int64
	ManifestRevision int64
	Current          bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
