// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_quota_usage.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertNodeQuotaUsage = `-- name: InsertNodeQuotaUsage :exec
INSERT INTO node_quota_usage (quota_period_id, node_id)
SELECT $1::uuid, node_id
FROM unnest($2::text[]) AS node_id
`

type InsertNodeQuotaUsageParams struct {
	QuotaPeriodID uuid.UUID
	NodeIds       []string
}

// Заводит нулевые строки расхода всем нодам fleet при открытии периода.
// Внутри уже открытого периода Apply строк не создаёт: ноде, добавленной в fleet
// позже, строку создаёт materialization job вместе с её FREEDOM access.
//
// Строки новые, конфликтующих locks они не берут, поэтому порядок вставки внутри
// одного оператора значения не имеет.
func (q *Queries) InsertNodeQuotaUsage(ctx context.Context, arg InsertNodeQuotaUsageParams) error {
	_, err := q.db.Exec(ctx, insertNodeQuotaUsage, arg.QuotaPeriodID, arg.NodeIds)
	return err
}

const lockNodeQuotaUsage = `-- name: LockNodeQuotaUsage :many

SELECT node_id, total_bytes, exhausted_at
FROM node_quota_usage
WHERE quota_period_id = $1
ORDER BY node_id
FOR UPDATE
`

type LockNodeQuotaUsageRow struct {
	NodeID      string
	TotalBytes  pgtype.Numeric
	ExhaustedAt *time.Time
}

// Расход трафика customer по нодам внутри периода.
// Блокирует строки расхода в порядке node_id. total_bytes —
// generated-колонка, поэтому читается, но не пишется.
func (q *Queries) LockNodeQuotaUsage(ctx context.Context, quotaPeriodID uuid.UUID) ([]LockNodeQuotaUsageRow, error) {
	rows, err := q.db.Query(ctx, lockNodeQuotaUsage, quotaPeriodID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockNodeQuotaUsageRow{}
	for rows.Next() {
		var i LockNodeQuotaUsageRow
		if err := rows.Scan(&i.NodeID, &i.TotalBytes, &i.ExhaustedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeQuotaExhausted = `-- name: SetNodeQuotaExhausted :exec
UPDATE node_quota_usage
SET exhausted_at = $3,
    updated_at = now()
WHERE quota_period_id = $1
  AND node_id = $2
`

type SetNodeQuotaExhaustedParams struct {
	QuotaPeriodID uuid.UUID
	NodeID        string
	ExhaustedAt   *time.Time
}

// Ставит и снимает отметку исчерпания под новый лимит в рамках того же периода.
// Непустой exhausted_at ставит отметку, NULL снимает её. Значение приходит
// из now() той же транзакции, поэтому отметка и решение о desired state опираются
// на один и тот же момент времени.
func (q *Queries) SetNodeQuotaExhausted(ctx context.Context, arg SetNodeQuotaExhaustedParams) error {
	_, err := q.db.Exec(ctx, setNodeQuotaExhausted, arg.QuotaPeriodID, arg.NodeID, arg.ExhaustedAt)
	return err
}
