// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quota_periods.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const closeOpenQuotaPeriod = `-- name: CloseOpenQuotaPeriod :exec
UPDATE quota_periods
SET closed_at = now()
WHERE customer_id = $1
  AND closed_at IS NULL
`

// Закрывает текущий период при renewal. closed_at берётся из now(), то есть из
// момента начала транзакции; ровно то же значение получает started_at нового
// периода, поэтому периоды образуют полуоткрытые интервалы [started_at, closed_at)
// без пересечения и без дыры, в которую провалилась бы дельта трафика (§11).
func (q *Queries) CloseOpenQuotaPeriod(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, closeOpenQuotaPeriod, customerID)
	return err
}

const insertQuotaPeriod = `-- name: InsertQuotaPeriod :exec
INSERT INTO quota_periods (
    quota_period_id, customer_id, started_at, usage_quota_bytes
) VALUES ($1, $2, now(), $3)
`

type InsertQuotaPeriodParams struct {
	QuotaPeriodID   uuid.UUID
	CustomerID      string
	UsageQuotaBytes pgtype.Numeric
}

// Открывает новый период. Partial unique index quota_periods_one_open_per_customer
// превращает пропущенный CloseOpenQuotaPeriod в ошибку транзакции, а не в двух
// открытых периодов сразу.
func (q *Queries) InsertQuotaPeriod(ctx context.Context, arg InsertQuotaPeriodParams) error {
	_, err := q.db.Exec(ctx, insertQuotaPeriod, arg.QuotaPeriodID, arg.CustomerID, arg.UsageQuotaBytes)
	return err
}

const lockOpenQuotaPeriod = `-- name: LockOpenQuotaPeriod :one

SELECT quota_period_id, customer_id, started_at, closed_at, usage_quota_bytes
FROM quota_periods
WHERE customer_id = $1
  AND closed_at IS NULL
FOR UPDATE
`

// Периоды учёта квоты (§5, §11).
// Блокирует текущий период — единственный с closed_at IS NULL (§11, §11.1 шаг 2).
// Отсутствие строки у существующего customer нарушает инвариант §11.
func (q *Queries) LockOpenQuotaPeriod(ctx context.Context, customerID string) (QuotaPeriod, error) {
	row := q.db.QueryRow(ctx, lockOpenQuotaPeriod, customerID)
	var i QuotaPeriod
	err := row.Scan(
		&i.QuotaPeriodID,
		&i.CustomerID,
		&i.StartedAt,
		&i.ClosedAt,
		&i.UsageQuotaBytes,
	)
	return i, err
}

const updateQuotaPeriodQuota = `-- name: UpdateQuotaPeriodQuota :exec
UPDATE quota_periods
SET usage_quota_bytes = $2
WHERE quota_period_id = $1
`

type UpdateQuotaPeriodQuotaParams struct {
	QuotaPeriodID   uuid.UUID
	UsageQuotaBytes pgtype.Numeric
}

// Меняет лимит открытого периода без сброса накопленного расхода (§5, правило 7).
func (q *Queries) UpdateQuotaPeriodQuota(ctx context.Context, arg UpdateQuotaPeriodQuotaParams) error {
	_, err := q.db.Exec(ctx, updateQuotaPeriodQuota, arg.QuotaPeriodID, arg.UsageQuotaBytes)
	return err
}
