// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const acceptNodeReconcile = `-- name: AcceptNodeReconcile :execrows
UPDATE vpn_nodes
SET reconciled_revision = $1,
    reconciled_at       = now()
WHERE node_id = $2::text
  AND desired_revision = $1
`

type AcceptNodeReconcileParams struct {
	DesiredRevision int64
	NodeID          string
}

// Принимает результат reconcile, если desired state ноды не уехал.
//
// Условие в WHERE, а не отдельным чтением, и по той же причине, что у
// SetAccessApplyState: только так проверка атомарна. Ноль строк означает, что
// desired_revision сдвинулась, пока мы ходили к агенту, — набор на проводе уже
// устарел, принимать его нельзя.
//
// Ревизия сравнивается ЗДЕСЬ, а не приезжает от агента: вендорный контракт
// ReconcileUsers её не передаёт и не возвращает.
func (q *Queries) AcceptNodeReconcile(ctx context.Context, arg AcceptNodeReconcileParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptNodeReconcile, arg.DesiredRevision, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNodeForReconcile = `-- name: ClaimNodeForReconcile :one

WITH claimed AS (
    UPDATE vpn_nodes
    SET reconcile_lease_owner      = $1::text,
        reconcile_lease_expires_at = now() + make_interval(secs => $2::int),
        reconcile_attempted_at     = now()
    WHERE node_id = (
        SELECT n.node_id
        FROM vpn_nodes n
        WHERE n.current
          AND (n.reconcile_lease_expires_at IS NULL OR n.reconcile_lease_expires_at < now())
          AND (
              n.needs_bootstrap
              OR n.reconcile_attempted_at IS NULL
              OR n.reconcile_attempted_at < now() - make_interval(secs => $3::int)
          )
        -- NULLS FIRST: нода, которую не reconcile-или ни разу, идёт вперёд всех.
        ORDER BY n.reconcile_attempted_at NULLS FIRST
        FOR UPDATE SKIP LOCKED
        LIMIT 1
    )
    -- needs_bootstrap возвращается ДО сброса: по нему шаг выбирает между полным
    -- набором и дешёвой сверкой инвентаря. Флаг снимает не захват, а
    -- принятый результат.
    RETURNING node_id, agent_config, public_config, desired_revision, needs_bootstrap
)
SELECT node_id, agent_config, public_config, desired_revision, needs_bootstrap FROM claimed
`

type ClaimNodeForReconcileParams struct {
	Owner              string
	LeaseSeconds       int32
	MinIntervalSeconds int32
}

type ClaimNodeForReconcileRow struct {
	NodeID          string
	AgentConfig     []byte
	PublicConfig    []byte
	DesiredRevision int64
	NeedsBootstrap  bool
}

// Authoritative reconcile: приведение ноды к точному desired state.
//
// Обычные изменения доставляет диспетчер по одному юзеру; эти запросы — про
// инициализацию и починку, то есть про случаи, когда доставлять уже нечего,
// потому что нода потеряла состояние целиком или разошлась с ним незаметно.
// Берёт ноду, которую пора reconcile-ить.
//
// Поводов два. needs_bootstrap — локальное состояние агента новое или
// повреждено, и без полного набора он не имеет права удалять юзеров, то есть
// сам из этого состояния не выйдет. Таймер — периодическая коррекция дрейфа:
// расхождение, о котором никто не сообщил, иначе жило бы вечно.
//
// Рост desired_revision поводом НЕ является: обычные изменения доставляет
// диспетчер, и полный набор на каждую команду customer был бы дороже её самой.
// Вендорный контракт говорит то же прямым текстом: «Normal changes use the two
// Ensure methods; this method is for initialization and recovery».
//
// reconcile_attempted_at ставится при захвате, а не по завершении: нода, у
// которой reconcile стабильно не удаётся, иначе опрашивалась бы циклом без пауз.
func (q *Queries) ClaimNodeForReconcile(ctx context.Context, arg ClaimNodeForReconcileParams) (ClaimNodeForReconcileRow, error) {
	row := q.db.QueryRow(ctx, claimNodeForReconcile, arg.Owner, arg.LeaseSeconds, arg.MinIntervalSeconds)
	var i ClaimNodeForReconcileRow
	err := row.Scan(
		&i.NodeID,
		&i.AgentConfig,
		&i.PublicConfig,
		&i.DesiredRevision,
		&i.NeedsBootstrap,
	)
	return i, err
}

const completeNodeOperationsByReconcile = `-- name: CompleteNodeOperationsByReconcile :exec
UPDATE agent_operations
SET status          = 'SUCCEEDED',
    completed_at    = now(),
    next_attempt_at = NULL,
    last_error_code = $1::text
WHERE node_id = $2::text
  AND status IN ('PENDING', 'RETRY_WAIT')
`

type CompleteNodeOperationsByReconcileParams struct {
	ErrorCode string
	NodeID    string
}

// Завершает операции ноды, которые reconcile уже удовлетворил.
//
// Только ожидающие: IN_FLIGHT держит другая горутина диспетчера, и трогать её
// строку значило бы дописывать результат за неё. Она завершится сама и увидит
// собственную повторную проверку desired_version.
//
// Условие безопасно ровно потому, что вызывающий уже прошёл гейт по
// desired_revision: раз ревизия ноды не менялась с момента чтения набора, любое
// изменение desired state любого её access тоже не происходило — оно обязано
// двигать ревизию. Значит каждая ожидающая операция несёт состояние, которое
// полный набор только что доставил.
func (q *Queries) CompleteNodeOperationsByReconcile(ctx context.Context, arg CompleteNodeOperationsByReconcileParams) error {
	_, err := q.db.Exec(ctx, completeNodeOperationsByReconcile, arg.ErrorCode, arg.NodeID)
	return err
}

const listNodeDesiredUsers = `-- name: ListNodeDesiredUsers :many
SELECT a.access_id,
       a.accounting_id,
       a.egress_key,
       a.encrypted_client_uuid,
       a.encryption_key_id
FROM vpn_accesses a
JOIN customer_entitlements e ON e.customer_id = a.customer_id
WHERE a.entry_node_id = $1::text
  AND a.retired_at IS NULL
  AND a.desired_state = 'PRESENT'
  AND e.expires_at > now()
  AND NOT EXISTS (
      SELECT 1
      FROM quota_periods p
      JOIN node_quota_usage u ON u.quota_period_id = p.quota_period_id
      WHERE p.customer_id = a.customer_id
        AND p.closed_at IS NULL
        AND u.node_id = a.entry_node_id
        AND u.exhausted_at IS NOT NULL
  )
ORDER BY a.access_id
`

type ListNodeDesiredUsersRow struct {
	AccessID            uuid.UUID
	AccountingID        string
	EgressKey           string
	EncryptedClientUuid []byte
	EncryptionKeyID     string
}

// Полный набор desired PRESENT юзеров ноды.
//
// «Фактически разрешённые» означает три ограничения, а не одно. Истёкшие
// entitlement и исчерпавшие node quota в набор не входят, ДАЖЕ если expiry или
// usage worker ещё не успели перевести их access в ABSENT: это требуется
// явно, а reconcile авторитетен — то, чего нет в наборе, агент удалит.
//
// Порядок по access_id, чтобы payload двух подряд идущих reconcile отличался
// только содержимым, а не перестановкой.
func (q *Queries) ListNodeDesiredUsers(ctx context.Context, nodeID string) ([]ListNodeDesiredUsersRow, error) {
	rows, err := q.db.Query(ctx, listNodeDesiredUsers, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeDesiredUsersRow{}
	for rows.Next() {
		var i ListNodeDesiredUsersRow
		if err := rows.Scan(
			&i.AccessID,
			&i.AccountingID,
			&i.EgressKey,
			&i.EncryptedClientUuid,
			&i.EncryptionKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeAccessesApplied = `-- name: MarkNodeAccessesApplied :exec
UPDATE vpn_accesses
SET apply_state = 'APPLIED'
WHERE entry_node_id = $1::text
  AND retired_at IS NULL
  AND (access_id = ANY($2::uuid[]) OR desired_state = 'ABSENT')
  AND apply_state <> 'APPLIED'
`

type MarkNodeAccessesAppliedParams struct {
	NodeID     string
	AppliedIds []uuid.UUID
}

// Отмечает применёнными те desired states ноды, которые reconcile удовлетворил.
//
// Два множества, и их различие существенно. Отправленные access теперь есть в
// Xray — это applied_ids. ABSENT-access теперь в Xray отсутствуют, потому что
// полный набор их не содержал, а всё лишнее агент удаляет, — это и есть
// авторитетность.
//
// А вот PRESENT-access, не попавший в набор из-за истёкшего entitlement или
// исчерпанной квоты, здесь НЕ отмечается: он удалён с ноды, но его desired_state
// всё ещё PRESENT, и APPLIED означал бы «на ноде ровно то, что заказано», что
// неправда. Его приведёт в порядок expiry или usage worker, сменив desired_state.
func (q *Queries) MarkNodeAccessesApplied(ctx context.Context, arg MarkNodeAccessesAppliedParams) error {
	_, err := q.db.Exec(ctx, markNodeAccessesApplied, arg.NodeID, arg.AppliedIds)
	return err
}

const releaseNodeReconcile = `-- name: ReleaseNodeReconcile :exec
UPDATE vpn_nodes
SET reconcile_lease_owner      = NULL,
    reconcile_lease_expires_at = NULL
WHERE node_id = $1::text
  AND reconcile_lease_owner = $2::text
`

type ReleaseNodeReconcileParams struct {
	NodeID string
	Owner  string
}

// Снимает собственный lease reconcile.
//
// Собственный: чужой мог быть взят после того, как наш протух, и снимать его
// значило бы пустить третьего к той же ноде.
func (q *Queries) ReleaseNodeReconcile(ctx context.Context, arg ReleaseNodeReconcileParams) error {
	_, err := q.db.Exec(ctx, releaseNodeReconcile, arg.NodeID, arg.Owner)
	return err
}

const setNodeNeedsBootstrap = `-- name: SetNodeNeedsBootstrap :exec
UPDATE vpn_nodes
SET needs_bootstrap = $1::boolean
WHERE node_id = $2::text
  AND needs_bootstrap <> $1::boolean
`

type SetNodeNeedsBootstrapParams struct {
	NeedsBootstrap bool
	NodeID         string
}

// Запоминает признак bootstrap, полученный от агента.
//
// Пишет pull worker: он и так разговаривает с каждой нодой каждые 15 секунд, а
// reconcile-воркер спит между заходами и узнал бы об этом с задержкой в целый
// интервал.
//
// Условие на неравенство существенно: без него каждый опрос каждой ноды писал бы
// новую версию строки vpn_nodes независимо от того, изменилось ли хоть что-то.
func (q *Queries) SetNodeNeedsBootstrap(ctx context.Context, arg SetNodeNeedsBootstrapParams) error {
	_, err := q.db.Exec(ctx, setNodeNeedsBootstrap, arg.NeedsBootstrap, arg.NodeID)
	return err
}
