// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topology.sql

package db

import (
	"context"
)

const bumpNodesDesiredRevision = `-- name: BumpNodesDesiredRevision :exec
UPDATE vpn_nodes
SET desired_revision = desired_revision + 1,
    updated_at = now()
WHERE node_id = ANY($1::text[])
`

// Увеличивает desired_revision ровно один раз на ноду независимо от числа
// затронутых access (§11.1). Вызывается только после LockNodesForUpdate, поэтому
// порядок строк внутри этого UPDATE уже не важен — все нужные locks взяты.
func (q *Queries) BumpNodesDesiredRevision(ctx context.Context, nodeIds []string) error {
	_, err := q.db.Exec(ctx, bumpNodesDesiredRevision, nodeIds)
	return err
}

const fleetIsCurrent = `-- name: FleetIsCurrent :one

SELECT EXISTS (
    SELECT 1
    FROM vpn_fleets
    WHERE vpn_fleet_id = $1
      AND current
) AS is_current
`

// Чтение текущей проекции топологии fleet и блокировка нод (§6, §11.1).
//
// Текущая топология — это строки проекции с current = true. Manifest является
// полным снапшотом, а его валидация требует существования всех node references
// (§6), поэтому глобально удалённая нода не может остаться ни в актуальном
// membership, ни в актуальной bridge-связи. Поддерживать этот инвариант обязан
// срез, применяющий manifest; здесь он не перепроверяется джойнами, чтобы
// определение «текущей топологии» жило в одном месте.
// Проверяет, что fleet присутствует в последнем принятом снапшоте (§5, правило 6).
// Ранее принятый fleet физически не удаляется (§6), поэтому строка может
// существовать с current = false: приём новых команд для него закрыт, а FK уже
// привязанных customer не ломается.
func (q *Queries) FleetIsCurrent(ctx context.Context, vpnFleetID int64) (bool, error) {
	row := q.db.QueryRow(ctx, fleetIsCurrent, vpnFleetID)
	var is_current bool
	err := row.Scan(&is_current)
	return is_current, err
}

const listCurrentFleetBridgeRoutes = `-- name: ListCurrentFleetBridgeRoutes :many
SELECT routing_key, entry_node_id, exit_node_id, egress_tag
FROM vpn_bridge_routes
WHERE vpn_fleet_id = $1
  AND current
ORDER BY routing_key
`

type ListCurrentFleetBridgeRoutesRow struct {
	RoutingKey  string
	EntryNodeID string
	ExitNodeID  string
	EgressTag   string
}

// BRIDGE-связи fleet. Каждая даёт один BRIDGE access на своей входной ноде;
// egress_tag форвардится агенту дословно (§6, §7).
func (q *Queries) ListCurrentFleetBridgeRoutes(ctx context.Context, vpnFleetID int64) ([]ListCurrentFleetBridgeRoutesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentFleetBridgeRoutes, vpnFleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentFleetBridgeRoutesRow{}
	for rows.Next() {
		var i ListCurrentFleetBridgeRoutesRow
		if err := rows.Scan(
			&i.RoutingKey,
			&i.EntryNodeID,
			&i.ExitNodeID,
			&i.EgressTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentFleetNodes = `-- name: ListCurrentFleetNodes :many
SELECT node_id
FROM vpn_fleet_nodes
WHERE vpn_fleet_id = $1
  AND current
ORDER BY node_id
`

// Ноды fleet. Каждая даёт один FREEDOM access (§4).
func (q *Queries) ListCurrentFleetNodes(ctx context.Context, vpnFleetID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listCurrentFleetNodes, vpnFleetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNodesForUpdate = `-- name: LockNodesForUpdate :many
SELECT node_id
FROM vpn_nodes
WHERE node_id = ANY($1::text[])
ORDER BY node_id
FOR UPDATE
`

// Блокирует строки нод, состав desired-юзеров которых меняется (§11.1, шаг 5).
// ORDER BY внутри FOR UPDATE обязателен: узел блокировки стоит в плане над
// сортировкой, поэтому строки блокируются в порядке node_id, и транзакции,
// затрагивающие пересекающиеся наборы нод, не встают в deadlock.
func (q *Queries) LockNodesForUpdate(ctx context.Context, nodeIds []string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockNodesForUpdate, nodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
