// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tx.sql

package db

import (
	"context"
	"time"
)

const selectTransactionNow = `-- name: SelectTransactionNow :one

SELECT now()::timestamptz AS now
`

// Общие для всех транзакций служебные запросы.
// Возвращает время начала транзакции. Выполняется первым оператором: now() внутри
// транзакции неизменен, поэтому одно это значение задаёт «сейчас» для всех
// доменных решений команды — истечения entitlement, отметок исчерпания квоты и
// границы периодов (решение 2, §11.1).
//
// Время процесса (app.Clock) для этого непригодно: расхождение часов приложения и
// базы означало бы, что closed_at старого периода и started_at нового разъедутся и
// дельта трафика не попадёт ни в один период (§11, §12).
func (q *Queries) SelectTransactionNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, selectTransactionNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}
