// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addNodeQuotaUsage = `-- name: AddNodeQuotaUsage :exec
UPDATE node_quota_usage
SET uplink_bytes   = uplink_bytes + $1,
    downlink_bytes = downlink_bytes + $2,
    updated_at     = now()
WHERE quota_period_id = $3
  AND node_id = $4::text
`

type AddNodeQuotaUsageParams struct {
	UplinkBytes   pgtype.Numeric
	DownlinkBytes pgtype.Numeric
	QuotaPeriodID uuid.UUID
	NodeID        string
}

// Добавляет дельты к counters ноды.
//
// Именно прибавление, а не запись: items приходят дельтами за интервал опроса, и
// агент — единственный владелец reset'а Xray-счётчиков. total_bytes считается
// generated-колонкой и здесь не пишется.
func (q *Queries) AddNodeQuotaUsage(ctx context.Context, arg AddNodeQuotaUsageParams) error {
	_, err := q.db.Exec(ctx, addNodeQuotaUsage,
		arg.UplinkBytes,
		arg.DownlinkBytes,
		arg.QuotaPeriodID,
		arg.NodeID,
	)
	return err
}

const advanceUsageCursor = `-- name: AdvanceUsageCursor :exec
UPDATE node_usage_cursors
SET spool_id       = $1::text,
    acked_sequence = $2,
    updated_at     = now()
WHERE node_id = $3::text
`

type AdvanceUsageCursorParams struct {
	SpoolID       string
	AckedSequence pgtype.Numeric
	NodeID        string
}

// Сдвигает подтверждённую позицию спула.
//
// Вызывается только после durable commit ВСЕХ групп batch: агент удаляет из спула
// ровно подтверждённое, и опережающее подтверждение потеряло бы неучтённый трафик.
//
// spool_id пишется вместе с sequence: смена спула означает новую нумерацию с нуля,
// и хранить старый id рядом с новым sequence нельзя.
func (q *Queries) AdvanceUsageCursor(ctx context.Context, arg AdvanceUsageCursorParams) error {
	_, err := q.db.Exec(ctx, advanceUsageCursor, arg.SpoolID, arg.AckedSequence, arg.NodeID)
	return err
}

const claimUsageNode = `-- name: ClaimUsageNode :one
UPDATE node_usage_cursors
SET lease_owner      = $1::text,
    lease_expires_at = now() + make_interval(secs => $2::int),
    updated_at       = now()
WHERE node_id = (
    SELECT c.node_id
    FROM node_usage_cursors c
    JOIN vpn_nodes n ON n.node_id = c.node_id AND n.current
    WHERE (c.lease_expires_at IS NULL
           OR c.lease_expires_at < now()
           OR c.lease_owner = $1::text)
      AND c.updated_at <= now() - make_interval(secs => $3::int)
    ORDER BY c.updated_at, c.node_id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING node_id, spool_id, acked_sequence,
          (SELECT agent_config FROM vpn_nodes WHERE node_id = node_usage_cursors.node_id) AS agent_config
`

type ClaimUsageNodeParams struct {
	Owner              string
	LeaseSeconds       int32
	MinIntervalSeconds int32
}

type ClaimUsageNodeRow struct {
	NodeID        string
	SpoolID       string
	AckedSequence pgtype.Numeric
	AgentConfig   []byte
}

// Берёт lease ноды, которую пора опросить.
//
// Условие на lease разрешает три случая: ничей, чужой протухший (воркер упал) и
// собственный. Последнее нужно, потому что каждый шаг идёт отдельной транзакцией.
//
// updated_at гейтит темп: чаще, чем агент опрашивает Xray, дёргать нечего — он
// вернёт пустой ответ. Он же задаёт порядок, поэтому давно не
// опрошенная нода идёт первой и ни одна не голодает.
//
// Ноды с current = false не опрашиваются: инфраструктура их уже погасила.
func (q *Queries) ClaimUsageNode(ctx context.Context, arg ClaimUsageNodeParams) (ClaimUsageNodeRow, error) {
	row := q.db.QueryRow(ctx, claimUsageNode, arg.Owner, arg.LeaseSeconds, arg.MinIntervalSeconds)
	var i ClaimUsageNodeRow
	err := row.Scan(
		&i.NodeID,
		&i.SpoolID,
		&i.AckedSequence,
		&i.AgentConfig,
	)
	return i, err
}

const ensureNodeQuotaUsageRow = `-- name: EnsureNodeQuotaUsageRow :exec
INSERT INTO node_quota_usage (quota_period_id, node_id)
VALUES ($1, $2::text)
ON CONFLICT (quota_period_id, node_id) DO NOTHING
`

type EnsureNodeQuotaUsageRowParams struct {
	QuotaPeriodID uuid.UUID
	NodeID        string
}

// Заводит строку расхода ноды, если её ещё нет.
//
// Отдельный запрос, а не InsertNodeQuotaUsage: там отсутствие строки является
// инвариантом и конфликт обязан провалить команду, а здесь наоборот — строки
// может не быть штатно. Истёкшему customer материализация их не создаёт, а
// начислять его items всё равно нужно, и без строки байты потерялись бы.
func (q *Queries) EnsureNodeQuotaUsageRow(ctx context.Context, arg EnsureNodeQuotaUsageRowParams) error {
	_, err := q.db.Exec(ctx, ensureNodeQuotaUsageRow, arg.QuotaPeriodID, arg.NodeID)
	return err
}

const ensureUsageCursors = `-- name: EnsureUsageCursors :exec

INSERT INTO node_usage_cursors (node_id, spool_id, updated_at)
SELECT node_id, '', 'epoch'
FROM vpn_nodes
WHERE current
ON CONFLICT (node_id) DO NOTHING
`

// Учёт трафика через pull от агента.
//
// Транзакций у шага три, и между первой и остальными идёт сетевой вызов:
// запрещает держать транзакцию открытой во время обращения к агенту. Batch
// обрабатывается не одной большой транзакцией, а группами
// (customer_id, node_id, quota_period_id) — по короткой транзакции на группу.
// Заводит строки курсора всем текущим нодам.
//
// Отдельным оператором перед claim, потому что claim обязан брать строку под
// FOR UPDATE SKIP LOCKED, а несуществующую строку заблокировать нельзя. Вставка
// идемпотентна и почти всегда не делает ничего.
//
// updated_at = 'epoch', а не now(): колонка означает «последняя попытка pull»,
// и новая нода обязана опрашиваться сразу, а не через интервал.
// spool_id пустой — агент игнорирует подтверждение чужого spool_id, поэтому первый
// pull безопасно уходит с ним.
func (q *Queries) EnsureUsageCursors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureUsageCursors)
	return err
}

const listCustomerNodeAccesses = `-- name: ListCustomerNodeAccesses :many
SELECT access_id, kind, logical_target_key, generation, entry_node_id,
       egress_key, accounting_id, desired_state, desired_version, retired_at
FROM vpn_accesses
WHERE customer_id = $1::text
  AND entry_node_id = $2::text
  AND retired_at IS NULL
ORDER BY access_id
`

type ListCustomerNodeAccessesParams struct {
	CustomerID  string
	EntryNodeID string
}

type ListCustomerNodeAccessesRow struct {
	AccessID         uuid.UUID
	Kind             string
	LogicalTargetKey string
	Generation       int32
	EntryNodeID      string
	EgressKey        string
	AccountingID     string
	DesiredState     string
	DesiredVersion   int64
	RetiredAt        *time.Time
}

// Все нератайрнутые access customer на одной входной ноде.
//
// Гасятся все, а не только тот, чей accounting_id приехал в batch:
// квота применяется к ноде целиком, а трафик всех FREEDOM и BRIDGE этого customer
// на ней суммируется в один node quota period.
//
// Без FOR UPDATE: корневая строка customer уже заблокирована, поэтому
// конкурирующего writer'а этих строк не существует.
func (q *Queries) ListCustomerNodeAccesses(ctx context.Context, arg ListCustomerNodeAccessesParams) ([]ListCustomerNodeAccessesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerNodeAccesses, arg.CustomerID, arg.EntryNodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerNodeAccessesRow{}
	for rows.Next() {
		var i ListCustomerNodeAccessesRow
		if err := rows.Scan(
			&i.AccessID,
			&i.Kind,
			&i.LogicalTargetKey,
			&i.Generation,
			&i.EntryNodeID,
			&i.EgressKey,
			&i.AccountingID,
			&i.DesiredState,
			&i.DesiredVersion,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNodeQuotaUsageRow = `-- name: LockNodeQuotaUsageRow :one
SELECT node_id, total_bytes, exhausted_at
FROM node_quota_usage
WHERE quota_period_id = $1
  AND node_id = $2::text
FOR UPDATE
`

type LockNodeQuotaUsageRowParams struct {
	QuotaPeriodID uuid.UUID
	NodeID        string
}

type LockNodeQuotaUsageRowRow struct {
	NodeID      string
	TotalBytes  pgtype.Numeric
	ExhaustedAt *time.Time
}

// Блокирует строку расхода одной ноды в периоде.
//
// Именно этот row lock сериализует несколько access одного customer на одной ноде,
// поэтому порог активируется ровно один раз.
func (q *Queries) LockNodeQuotaUsageRow(ctx context.Context, arg LockNodeQuotaUsageRowParams) (LockNodeQuotaUsageRowRow, error) {
	row := q.db.QueryRow(ctx, lockNodeQuotaUsageRow, arg.QuotaPeriodID, arg.NodeID)
	var i LockNodeQuotaUsageRowRow
	err := row.Scan(&i.NodeID, &i.TotalBytes, &i.ExhaustedAt)
	return i, err
}

const lockQuotaPeriodAt = `-- name: LockQuotaPeriodAt :one
SELECT quota_period_id, customer_id, started_at, closed_at, usage_quota_bytes
FROM quota_periods
WHERE customer_id = $1::text
  AND started_at <= $2
  AND (closed_at IS NULL OR $2 < closed_at)
FOR UPDATE
`

type LockQuotaPeriodAtParams struct {
	CustomerID  string
	CollectedAt time.Time
}

// Блокирует период, в который попадает момент сбора batch.
//
// Границы полуоткрыты: started_at <= collected_at < closed_at. Открытый период
// закрывающей границы не имеет. Ноль строк означает, что подходящего периода нет
// вовсе, — такой item уходит в карантин, а не в IGNORED_CLOSED_PERIOD, потому что
// период не закрыт, его не существует.
func (q *Queries) LockQuotaPeriodAt(ctx context.Context, arg LockQuotaPeriodAtParams) (QuotaPeriod, error) {
	row := q.db.QueryRow(ctx, lockQuotaPeriodAt, arg.CustomerID, arg.CollectedAt)
	var i QuotaPeriod
	err := row.Scan(
		&i.QuotaPeriodID,
		&i.CustomerID,
		&i.StartedAt,
		&i.ClosedAt,
		&i.UsageQuotaBytes,
	)
	return i, err
}

const pruneProcessedUsageItems = `-- name: PruneProcessedUsageItems :execrows
DELETE FROM traffic_usage_items_processed
WHERE ctid IN (
    SELECT p.ctid
    FROM traffic_usage_items_processed p
    JOIN node_usage_cursors c ON c.node_id = p.node_id
    -- make_interval, а не умножение на interval '1 second': из выражения с
    -- умножением sqlc выводит имя параметра по всей его записи и тип interface{}.
    WHERE p.processed_at < now() - make_interval(secs => $1::double precision)
      AND (p.spool_id <> c.spool_id OR p.sequence <= c.acked_sequence)
    ORDER BY p.processed_at
    LIMIT $2::bigint
)
`

type PruneProcessedUsageItemsParams struct {
	RetentionSeconds float64
	MaxRows          int64
}

// Удаляет дедуп-записи, которые больше не могут понадобиться (ретенция).
//
// Строка реестра нужна ровно до тех пор, пока агент способен прислать тот же
// batch повторно. Способен он на это, пока не получил наше подтверждение:
// acknowledged_usage_through уезжает следующим GetNodeState, и до тех пор batch
// лежит у него в спуле. Отсюда два условия, любого из которых достаточно:
//
//   - spool_id не тот, что у ноды сейчас, — прежнего спула физически нет, и
//     прислать из него уже нечего;
//   - sequence не выше подтверждённого — этот batch агенту уже подтверждён.
//
// Возраст — третье условие, и оно про НАС, а не про агента: подтверждение может
// быть записано у нас, но ещё не доехать до ноды, если backend в этот момент
// лежит. Окно должно перекрывать такой простой. Повтор, приехавший позже окна,
// начислится второй раз — называет это принятой положительной погрешностью.
//
// Пачками, а не одним оператором: таблица растёт на активного пользователя
// каждые 15 секунд, и накопленное за сутки одним DELETE означало бы длинную
// транзакцию и раздутую таблицу.
//
// Строки ноды, у которой нет строки курсора, не удаляются никогда: без курсора
// нечем доказать подтверждение. Появиться такие не могут — курсор заводится при
// первом claim ноды, то есть заведомо раньше обработки любого её batch.
//
// Адресация по ctid, а не по первичному ключу, и это не микрооптимизация. С
// ключом планировщик сводит внешний DELETE с подзапросом в hash semi join и
// читает ВСЮ таблицу, чтобы найти в ней найденные же строки: 305 тысяч строк и
// 2851 буфер против 55 у самого подзапроса (проверено EXPLAIN ANALYZE). То есть
// стоимость уборки осталась бы пропорциональна тому, что она убирает, и индекс
// по processed_at не дал бы ничего. С ctid остаётся Tid Scan — обращение к
// странице на строку, ровно размер пачки, независимо от размера таблицы.
//
// Физический адрес безопасен здесь по трём причинам: подзапрос и удаление
// выполняются одним оператором под одним снимком; строки этой таблицы никогда не
// обновляются, поэтому ctid не может съехать под нами; переиспользованный после
// VACUUM адрес указывал бы на строку новее снимка, а такая невидима и не
// удаляется.
func (q *Queries) PruneProcessedUsageItems(ctx context.Context, arg PruneProcessedUsageItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneProcessedUsageItems, arg.RetentionSeconds, arg.MaxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const quarantineUsageItems = `-- name: QuarantineUsageItems :exec
INSERT INTO traffic_batch_quarantine (
    node_id, spool_id, sequence, accounting_id, reason, sanitized_payload
)
SELECT $1::text, $2::text, $3::numeric, a.accounting_id, $4::text,
       jsonb_build_object('uplink_bytes', u.uplink, 'downlink_bytes', d.downlink)
FROM unnest($5::text[]) WITH ORDINALITY AS a(accounting_id, ord)
JOIN unnest($6::numeric[]) WITH ORDINALITY AS u(uplink, ord) ON u.ord = a.ord
JOIN unnest($7::numeric[]) WITH ORDINALITY AS d(downlink, ord) ON d.ord = a.ord
`

type QuarantineUsageItemsParams struct {
	NodeID        string
	SpoolID       string
	Sequence      pgtype.Numeric
	Reason        string
	AccountingIds []string
	Uplinks       []pgtype.Numeric
	Downlinks     []pgtype.Numeric
}

// Кладёт items в карантин.
//
// sanitized_payload собирается ЗДЕСЬ, а не приходит из Go: так в него физически не
// может попасть ничего, кроме счётчиков байтов. Ни client_uuid, ни IP, ни
// назначение в usage не приходят вовсе, но карантин — последнее место, где
// стоит полагаться на дисциплину вызывающего.
func (q *Queries) QuarantineUsageItems(ctx context.Context, arg QuarantineUsageItemsParams) error {
	_, err := q.db.Exec(ctx, quarantineUsageItems,
		arg.NodeID,
		arg.SpoolID,
		arg.Sequence,
		arg.Reason,
		arg.AccountingIds,
		arg.Uplinks,
		arg.Downlinks,
	)
	return err
}

const registerProcessedUsageItems = `-- name: RegisterProcessedUsageItems :many
INSERT INTO traffic_usage_items_processed (
    node_id, spool_id, sequence, accounting_id, access_id, quota_period_id, result
)
SELECT $1::text, $2::text, $3::numeric,
       a.accounting_id, i.access_id, $4::uuid, $5::text
FROM unnest($6::text[]) WITH ORDINALITY AS a(accounting_id, ord)
JOIN unnest($7::uuid[]) WITH ORDINALITY AS i(access_id, ord) ON i.ord = a.ord
ON CONFLICT DO NOTHING
RETURNING accounting_id
`

type RegisterProcessedUsageItemsParams struct {
	NodeID        string
	SpoolID       string
	Sequence      pgtype.Numeric
	QuotaPeriodID uuid.UUID
	Result        string
	AccountingIds []string
	AccessIds     []uuid.UUID
}

// Регистрирует items в реестре идемпотентности и возвращает только НОВЫЕ.
//
// ON CONFLICT DO NOTHING RETURNING — это и есть дедуп: попадание означает, что item
// уже начислен, и повторный pull, перезапуск воркера или повтор batch его не
// удвоят. Начисляются counters только по возвращённым строкам.
// Параллельные массивы сшиваются через WITH ORDINALITY: многоаргументный unnest
// разбирается только PostgreSQL, но не парсером sqlc.
func (q *Queries) RegisterProcessedUsageItems(ctx context.Context, arg RegisterProcessedUsageItemsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, registerProcessedUsageItems,
		arg.NodeID,
		arg.SpoolID,
		arg.Sequence,
		arg.QuotaPeriodID,
		arg.Result,
		arg.AccountingIds,
		arg.AccessIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var accounting_id string
		if err := rows.Scan(&accounting_id); err != nil {
			return nil, err
		}
		items = append(items, accounting_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerQuarantinedUsageItems = `-- name: RegisterQuarantinedUsageItems :exec
INSERT INTO traffic_usage_items_processed (
    node_id, spool_id, sequence, accounting_id, result
)
SELECT $1::text, $2::text, $3::numeric, accounting_id, 'QUARANTINED'
FROM unnest($4::text[]) AS accounting_id
ON CONFLICT DO NOTHING
`

type RegisterQuarantinedUsageItemsParams struct {
	NodeID        string
	SpoolID       string
	Sequence      pgtype.Numeric
	AccountingIds []string
}

// Регистрирует карантинные items как обработанные.
//
// access_id и quota_period_id остаются NULL: у неизвестного accounting_id владельца
// нет, а у item без подходящего периода — периода. Отметка нужна, чтобы один плохой
// item не блокировал batch навсегда.
func (q *Queries) RegisterQuarantinedUsageItems(ctx context.Context, arg RegisterQuarantinedUsageItemsParams) error {
	_, err := q.db.Exec(ctx, registerQuarantinedUsageItems,
		arg.NodeID,
		arg.SpoolID,
		arg.Sequence,
		arg.AccountingIds,
	)
	return err
}

const releaseUsageLease = `-- name: ReleaseUsageLease :exec
UPDATE node_usage_cursors
SET lease_owner      = NULL,
    lease_expires_at = NULL
WHERE node_id = $1::text
  AND lease_owner = $2::text
`

type ReleaseUsageLeaseParams struct {
	NodeID string
	Owner  string
}

// Снимает lease по завершении шага.
//
// Без явного снятия нода простаивала бы до истечения TTL: он с запасом перекрывает
// весь шаг вместе с RPC и потому заметно длиннее интервала опроса.
//
// Условие на владельца обязательно: чужой lease снимать нельзя, иначе воркер,
// задержавшийся на своём шаге, потерял бы ноду в пользу второго.
func (q *Queries) ReleaseUsageLease(ctx context.Context, arg ReleaseUsageLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseUsageLease, arg.NodeID, arg.Owner)
	return err
}

const resolveAccountingIDs = `-- name: ResolveAccountingIDs :many
SELECT accounting_id, access_id, customer_id, entry_node_id
FROM vpn_accesses
WHERE accounting_id = ANY ($1::text[])
`

type ResolveAccountingIDsRow struct {
	AccountingID string
	AccessID     uuid.UUID
	CustomerID   string
	EntryNodeID  string
}

// Сопоставляет accounting_id с их владельцами.
//
// Ретайрнутые и погашенные access тоже возвращаются: учитывать их разрешено
// items после expiry/retire, а accounting_id уникален и не переиспользуется,
// поэтому исторический маппинг — это просто чтение vpn_accesses без фильтров.
// Ненайденные accounting_id уходят в карантин.
func (q *Queries) ResolveAccountingIDs(ctx context.Context, accountingIds []string) ([]ResolveAccountingIDsRow, error) {
	rows, err := q.db.Query(ctx, resolveAccountingIDs, accountingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolveAccountingIDsRow{}
	for rows.Next() {
		var i ResolveAccountingIDsRow
		if err := rows.Scan(
			&i.AccountingID,
			&i.AccessID,
			&i.CustomerID,
			&i.EntryNodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
